Fix/join unique event data
Open-Dataplatform/osiris-sdk pull request #32
Opened 2021-11-09 10:57 UTC by jensrix

Problemet med koden inden denne ændring er, at man hvis data er blevet opdateret i kilden og man genkører adapter/transformation, så vil man beholde rækker med gammel data. Og man vil ikke kunne se hvilken række der er den nye.
Med ændringen her vil gamle rækker blive opdateret.

2021-11-16 14:10 UTC, jensrix commented
Note: Jeg har kun lavet ændringer i src/osiris/pipelines/transformations.py. De andre ændringer er med, fordi test var forskellig fra main.

2021-11-19 11:51 UTC, runethorbek commented on src/osiris/pipelines/transformations.py
> +    def __init__(self, datasets: Dataset, time_resolution: TimeResolution, index_columns: list):
Problemet med dette er, at alle transformationer skal have angivet denne liste. En mulighed er at det bliver optional.
Derudover skal vi på alle transformationer kunne angive denne liste. For den generiske transformation, skal dette gøres via conf.ini. Det skal også implementeres før dette kan merges.

Jeg ser ikke noget problem i det, men vi kan ikke gøre det uden vi har taget stilling til det.

2021-11-19 12:23 UTC, andbo requested changes
Small changes.

2021-11-19 12:23 UTC, andbo commented on src/osiris/pipelines/transformations.py
>              processed_events = json.loads(processed_events.to_json(orient='records'))
```suggestion
            processed_events = processed_events.to_dict(orient='records')
```

2021-11-19 12:23 UTC, andbo commented on src/osiris/pipelines/transformations.py
> +            processed_events.drop_duplicates(inplace=True, ignore_index=True, subset=self.index_columns)
```suggestion
            processed_events.drop_duplicates(inplace=True, ignore_index=True, subset=self.index_columns, keep='first')
```
add keep first to be clear about it.

2021-11-19 12:23 UTC, andbo commented on src/osiris/pipelines/transformations.py
> +    def __init__(self, datasets: Dataset, time_resolution: TimeResolution, index_columns: list):
```suggestion
    def __init__(self, datasets: Dataset, time_resolution: TimeResolution, index_columns: list=None):
```
Added default option to be non breaking.

2021-11-22 06:39 UTC, runethorbek commented on src/osiris/pipelines/transformations.py
> +            processed_events.drop_duplicates(inplace=True, ignore_index=True, subset=self.index_columns)
Jeg går ud fra, at hvis self.index_columns er None, så tjekker den på alle columns?

2021-11-22 09:21 UTC, jensrix commented on src/osiris/pipelines/transformations.py
> +            processed_events.drop_duplicates(inplace=True, ignore_index=True, subset=self.index_columns)
Ja lige præcis. Så skal rækkerne være helt identiske for at nogle af dem smides væk.

2021-11-25 15:16 UTC, runethorbek approved these changes

2021-11-25 15:24 UTC, merged