Add posibility to use access token instead of service principal
Open-Dataplatform/osiris-sdk pull request #7
Opened 2021-08-18 12:47 UTC by KasperDamgaard

Det nye kan bruges med:

``` python
accessToken = AccessToken("{token-value}", 1629292678)
clientAuth = ClientAuthorization(tenant_id=None, client_id=None, client_secret=None, access_token=accessToken)
```

Har testet det meget lidt (kaldt dmi med egress)

2021-08-18 19:21 UTC, ragerin commented
Så smukt! Har lagt lidt kommentarer ind. 

Har du kørt tox på koden?

2021-08-19 05:42 UTC, KasperDamgaard commented
@ragerin Jeg aner ikke hvad tox er, så nej :D - Kort guide til det?

2021-08-19 05:43 UTC, KasperDamgaard commented
also - kan ikke se dine kommentarer. Måske du ikke har afsluttet dit review?

2021-08-20 13:16 UTC, ragerin requested changes

2021-08-23 06:57 UTC, KasperDamgaard commented
@ragerin Jeg har fixet de tox fejl jeg kunne forstå. Den fejler stadig på py3, men tror det er en lokal fejl på min maskine. Kan ikke se hvad problemet er i hvert fald. 
Vil du dobbelttjekke igen?

2021-08-23 13:14 UTC, merged